---
driver:
  name: podman
platforms:
  - name: cs9
    image: quay.io/centos/centos:stream9
    pre_build_image: true
  - name: f41
    image: quay.io/fedora/fedora:41
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
